POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "fajar",
  "email": "fajar123@email.com",
  "password": "passwordku",
  "identityType": "KTP",
  "identityNumber": "312367061",
  "address": "jalan teguh"
}

###
GET http://localhost:3000/api/v1/users?limit=5&page=1


###
GET http://localhost:3000/api/v1/users/17

###
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "balance": 30000,
    "bankName": "BRI",
    "bankAccountNumber": "0192139433",
    "userId": 17
}


###
GET http://localhost:3000/api/v1/accounts?limit=3&page=1


###
GET http://localhost:3000/api/v1/accounts/1


###
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
  "amount": 1000,
  "sourceAccountId": 5,
  "destinationAccountId": 4
}


###
GET http://localhost:3000/api/v1/transactions?limit=2&page=1



###
GET http://localhost:3000/api/v1/transactions/1



