POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "fajar",
  "email": "fajar123@email.com",
  "password": "passwordku",
  "identityType": "KTP",
  "identityNumber": "312367061",
  "address": "jalan teguh"
}

###
GET http://localhost:3000/api/v1/users?limit=5&page=1


###
GET http://localhost:3000/api/v1/users/17

###
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "balance": 30000,
    "bankName": "BRI",
    "bankAccountNumber": "0192139433",
    "userId": 17
}


###
GET http://localhost:3000/api/v1/accounts?limit=3&page=1


###
GET http://localhost:3000/api/v1/accounts/1


###
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
  "amount": 100,
  "sourceAccountId": 4,
  "destinationAccountId": 5
}


###
GET http://localhost:3000/api/v1/transactions?limit=2&page=1



###
GET http://localhost:3000/api/v1/transactions/1



# jwt token autentikasi
###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name":"niko",
    "email":"niko@mail.com",
    "password":"niko123",
    "password_confirmation":"niko123"
}


###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"niko@mail.com",
    "password":"niko123"
}


###
GET http://localhost:3000/api/v1/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsImlhdCI6MTY5Nzc5MzM3NH0.8t_mPZEt40LJeONcaefM6DCLp0hT7c8z1C45l9mWkcc



